services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes: # kopierer fra stien lokalt : til filstien i Docker-container
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf 
    depends_on: # avhengighet mellom tjeneste
      - api

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5001:8080" # 5000 er opptatt 
    environment:
      - MYSQL_HOST=db # kobles til db-service (samme nettverk) i docker-compose
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DB=mydb # navnet på databasen API-et skal kobles til (kalt 'mydb' i dette tilfellet)
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
    volumes:  # kopierer fra stien lokalt : til filstien i Docker-container
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql